name: CMake

on:
  push:
    branches: [ main ]

concurrency:
  group: build
  cancel-in-progress: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
        
        - os: ubuntu-latest
          extension: so
          out: GITHUB_ACTIONS_PREBUILD_OUT_FOLDER/ubuntu-latest
          listLibs: find GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER -name \*.so
          mkdir: mkdir GITHUB_ACTIONS_PREBUILD_OUT_FOLDER; mkdir GITHUB_ACTIONS_PREBUILD_OUT_FOLDER/ubuntu-latest
          copyLibs: find GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER -name \*.so -exec cp -v {} GITHUB_ACTIONS_PREBUILD_OUT_FOLDER/ubuntu-latest \;
          rm: rm -rf GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER
          
        - os: macOS-latest
          extension: dylib
          out: GITHUB_ACTIONS_PREBUILD_OUT_FOLDER/macOS-latest
          listLibs: find GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER -name \*.dylib
          mkdir: mkdir GITHUB_ACTIONS_PREBUILD_OUT_FOLDER; mkdir GITHUB_ACTIONS_PREBUILD_OUT_FOLDER/macOS-latest
          copyLibs: find GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER -name \*.dylib -exec cp -v {} GITHUB_ACTIONS_PREBUILD_OUT_FOLDER/macOS-latest \;
          rm: rm -rf GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER
          
        - os: windows-latest
          extension: dll
          out: GITHUB_ACTIONS_PREBUILD_OUT_FOLDER/windows-latest
          listLibs: Get-ChildItem -path GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER -r -filter *.dll
          mkdir: mkdir GITHUB_ACTIONS_PREBUILD_OUT_FOLDER; mkdir GITHUB_ACTIONS_PREBUILD_OUT_FOLDER/windows-latest
          copyLibs: Get-ChildItem -path GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER -r -filter *.dll | Copy-Item -v -Destination GITHUB_ACTIONS_PREBUILD_OUT_FOLDER/windows-latest
          rm: Remove-Item -Recurse -Force GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER

    steps:
    - uses: actions/checkout@v2
    
    - name: pull
      run: |
        git pull
        git status

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        cmake -D GITHUB_ACTIONS_PREBUILD_EXTENSION=${{matrix.extension}} -B GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        git status

    - name: Build
      # Build your program with the given configuration
      run: |
        cmake --build GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER --config ${{env.BUILD_TYPE}}
        git status
      
    - name: list libs
      run: |
        ${{matrix.listLibs}}
        git status
      
    - name: git config global
      run: |
        git config --global user.email "GITHUB_ACTIONS_PREBUILD";
        git config --global user.name "GITHUB_ACTIONS_PREBUILD"
        git status
        
    - name: mkdir
      continue-on-error: true
      run: |
        ${{matrix.mkdir}}
        git status
        
    - name: copy files
      run: |
        ${{matrix.copyLibs}}
        git status
        
    - name: rm build
      run: |
        ${{matrix.rm}}
        git status
      
    - name: add prebuilt
      run: |
        git add -Av GITHUB_ACTIONS_PREBUILD_OUT_FOLDER
        git status
        
    - name: commit
      run: |
        git commit -m "automated push of prebuilt binaries"
        git status
        
    - name: push
      run: |
        git push
        git status
