name: CMake

on:
  push:
    branches: [ main ]

concurrency:
  group: build
  cancel-in-progress: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  
  # Customize the build folder here
  # IMPORTANT: this MUST NOT conflict with any existing folders
  
  GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER: GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER

  # Customize the output folder here
  # IMPORTANT: this MUST NOT conflict with any existing folders
  
  GITHUB_ACTIONS_PREBUILD_OUT_FOLDER: GITHUB_ACTIONS_PREBUILD_OUT_FOLDER
  
  # Set this to true in order to publish builds to dedicated repos
  # this has the advantage of keeping repository size minimal
  # history is also kept minimal to reduce total repo size
  
  # IMPORTANT: this requires a REPO_ACCESS_TOKEN
  
  PUSH_TO_EXTERNAL_REPO: true

  # Customize the external repo output folder here
  # IMPORTANT: this MUST NOT conflict with any existing folders
  
  GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER: GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
        
        - os: ubuntu-latest
          extension: so
          get_chmod: stat --format \"%a\"

        - os: macOS-latest
          extension: dylib
          get_chmod: stat -f \"%OLp\"

        - os: windows-latest
          extension: dll
          get_chmod: stat --format \"%a\"

    defaults:
      run:
        shell: bash
        env:
          SECRET_TOKEN: ${{secrets.REPO_ACCESS_TOKEN}}
#      env:
        # Put your secret here
        # to create a secret, go to

        # User Profile -> Settings ->
        # Developer Settings (at the bottom of page) -> Persional Access Tokens

        # then generate a new token and give it [public_repo] scope and then
        # click [Generate token]
        # finally copy its token id

        # next, go to your repository containing this workflow
        # Settings -> Environments -> New Environment

        # give your new environment a name and then click [Configure Environment]

        # scroll down to [Environment secrets] and click [Add Secret]

        # in the [Value] field, past the token id that you copied earlier

        # in the [Name] field, enter a name, replacing spaces with underscore (_)
        # for example, we will name it REPO_ACCESS_TOKEN

        # and then enter it here as ${{secrets.REPO_ACCESS_TOKEN}}

#        REPO_ACCESS_TOKEN: ${{secrets.REPO_ACCESS_TOKEN}}

    steps:
    - uses: actions/checkout@v2
    
    - name: pull
      run: |
        git pull
        git status
        
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        cmake -D GITHUB_ACTIONS_PREBUILD_EXTENSION=${{matrix.extension}} -B ${{env.GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        git status

    - name: Build
      # Build your program with the given configuration
      run: |
        cmake --build ${{env.GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER}} --config ${{env.BUILD_TYPE}}
        git status
      
    - name: list libs
      run: |
        find ${{env.GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER}} -name \*.${{matrix.extension}}
        git status
      
    - name: git config global
      run: |
        git config --global user.email "GITHUB_ACTIONS_PREBUILD";
        git config --global user.name "GITHUB_ACTIONS_PREBUILD"
        git status
        
    - name: mkdir ${{env.GITHUB_ACTIONS_PREBUILD_OUT_FOLDER}}
      continue-on-error: true
      run: |
        mkdir ${{env.GITHUB_ACTIONS_PREBUILD_OUT_FOLDER}}
        git status
        
    - name: mkdir ${{env.GITHUB_ACTIONS_PREBUILD_OUT_FOLDER}}/${{matrix.os}}
      continue-on-error: true
      run: |
        mkdir ${{env.GITHUB_ACTIONS_PREBUILD_OUT_FOLDER}}/${{matrix.os}}
        git status

    - name: copy files
      run: |
        find ${{env.GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER}} -name \*.${{matrix.extension}} -exec cp -v {} ${{env.GITHUB_ACTIONS_PREBUILD_OUT_FOLDER}}/${{matrix.os}}/ \;
        git status
        
    - name: rm build
      run: |
        rm -rf ${{env.GITHUB_ACTIONS_PREBUILD_BUILD_FOLDER}}
        git status
        
    - name: split files
      run: |
        chmod +x ./split_files.sh
        ./split_files.sh ${{env.GITHUB_ACTIONS_PREBUILD_OUT_FOLDER}}/${{matrix.os}} ${{matrix.extension}} "${{matrix.get_chmod}}"
        git status

    - name: add files for CURRENT REPO
      run: |
        git add -Av ${{env.GITHUB_ACTIONS_PREBUILD_OUT_FOLDER}}/${{matrix.os}}
        git status
      if: env.PUSH_TO_EXTERNAL_REPO == 'false'
      
    - name: commit for CURRENT REPO
      continue-on-error: true
      run: |
        git commit -m "push prebuilts for ${{matrix.os}}"
        git status
      if: env.PUSH_TO_EXTERNAL_REPO == 'false'

    - name: push for CURRENT REPO
      run: |
        git push
        git status
      if: env.PUSH_TO_EXTERNAL_REPO == 'false'
      
    - name: clone EXTERNAL REPO
      run: |
        git clone https://github.com/${{github.repository}}-${{matrix.os}} ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}}
      if: env.PUSH_TO_EXTERNAL_REPO == 'true'

    - name: create branch if needed for EXTERNAL REPO
      env:
        REPO_ACCESS_TOKEN: ${{secrets.REPO_ACCESS_TOKEN}}
      run: |
        cd ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}}
        cat DO_NOT_DELETE_ME.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_RESET_POINT || (touch DO_NOT_DELETE_ME.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_RESET_POINT; git add DO_NOT_DELETE_ME.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_RESET_POINT; git commit -m "GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_RESET_POINT"; git remote set-url origin https://github.com/${{github.repository}}-${{matrix.os}}.git; git branch -M main; git push https://${{github.repository_owner}}:${REPO_ACCESS_TOKEN}@github.com/${{github.repository}}-${{matrix.os}})
      if: env.PUSH_TO_EXTERNAL_REPO == 'true'

    - name: add files for EXTERNAL REPO
      run: |
        mv ${{env.GITHUB_ACTIONS_PREBUILD_OUT_FOLDER}}/${{matrix.os}}/* ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}}
        cd ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}}
        git add -Av
      if: env.PUSH_TO_EXTERNAL_REPO == 'true'

    - name: commit for EXTERNAL REPO
      continue-on-error: true
      run: |
        cd ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}}
        git commit -m "push prebuilts for ${{matrix.os}}"
        git status
      if: env.PUSH_TO_EXTERNAL_REPO == 'true'

    - name: push for EXTERNAL REPO
      env:
        REPO_ACCESS_TOKEN: ${{secrets.REPO_ACCESS_TOKEN}}
      run: |
        cd ${{env.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER}}
        git push https://${{github.repository_owner}}:${REPO_ACCESS_TOKEN}@github.com/${{github.repository}}-${{matrix.os}} -u origin main
        git status
      if: env.PUSH_TO_EXTERNAL_REPO == 'true'
